version: '2.4'

services:
  octoprint:
    image: octoprint/octoprint:1.3.6
    restart: unless-stopped
    ports:
      - 50002:5000
    volumes:
     - ./config:/home/octoprint/.octoprint


volumes:
  octoprint:
